//! PNG tEXt-chunk metadata writer for generated images.
//!
//! Reproducibility contract: every generated PNG carries enough information in
//! its tEXt chunks for a future caller to regenerate (or audit) it from the
//! file alone — `prompt`, `model`, the JSON-encoded params blob, and the app
//! `version`. The same JSON blob is duplicated in the DB row's `params_json`
//! column so listing doesn't have to crack open the file.
//!
//! Only compiled into the build when the real engine is — the stub never
//! reaches this module.

use serde::Serialize;

/// Reproducible-generation manifest embedded as `prompt`, `model`,
/// `params_json`, and `version` tEXt chunks. JSON-serialized to a single
/// chunk because PNG tEXt is key/value with no structured value type.
#[derive(Clone, Debug, Serialize)]
pub struct PngMetadata<'a> {
    pub prompt: &'a str,
    pub model: &'a str,
    /// Width × height in pixels.
    pub width: u32,
    pub height: u32,
    pub steps: u32,
    pub cfg: f32,
    pub seed: u64,
    pub offload: bool,
}

impl<'a> PngMetadata<'a> {
    /// Serialize the param fields (everything except prompt/model — which get
    /// their own chunks) to a compact JSON object for the `params_json` chunk
    /// AND for the DB row's `params_json` column.
    pub fn params_json(&self) -> String {
        // Hand-rolled so the field order is deterministic across runs (no
        // serde_json::Map non-determinism). Cheap — there are seven keys.
        format!(
            "{{\"width\":{},\"height\":{},\"steps\":{},\"cfg\":{},\"seed\":{},\"offload\":{}}}",
            self.width, self.height, self.steps, self.cfg, self.seed, self.offload,
        )
    }
}

/// App version string burned into the `version` tEXt chunk so a future Froglips
/// can warn when re-running a PNG generated by an incompatible engine build.
pub fn app_version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

/// Encode an RGB8 buffer to a PNG byte vector with the metadata tEXt chunks
/// already populated. The buffer must be `width * height * 3` bytes — caller's
/// responsibility to upholds (the engine produces this exact shape from
/// `DynamicImage::ImageRgb8`).
///
/// The output is returned as an owned `Vec<u8>` rather than written to disk;
/// the IPC layer's atomic-write helper picks where to land it (`.tmp` →
/// `fsync` → `rename`) so the encoder stays I/O-free and easy to unit-test.
#[cfg(all(
    feature = "native-mistralrs",
    target_os = "macos",
    target_arch = "aarch64"
))]
pub fn encode_with_metadata(
    rgb8: &[u8],
    width: u32,
    height: u32,
    meta: &PngMetadata<'_>,
) -> Result<Vec<u8>, String> {
    use png::text_metadata::ZTXtChunk;

    let expected = (width as usize)
        .checked_mul(height as usize)
        .and_then(|n| n.checked_mul(3))
        .ok_or_else(|| "image dimensions overflow".to_string())?;
    if rgb8.len() != expected {
        return Err(format!(
            "rgb buffer length {} != width*height*3 ({})",
            rgb8.len(),
            expected
        ));
    }

    let mut out = Vec::with_capacity(rgb8.len() / 4);
    {
        let mut encoder = png::Encoder::new(&mut out, width, height);
        encoder.set_color(png::ColorType::Rgb);
        encoder.set_depth(png::BitDepth::Eight);
        // Compress the metadata chunks (ZTXt) — they're small and the encoder
        // accepts them before the IDAT stream begins.
        encoder
            .add_ztxt_chunk("prompt".to_string(), meta.prompt.to_string())
            .map_err(|e| format!("png prompt chunk: {e}"))?;
        encoder
            .add_ztxt_chunk("model".to_string(), meta.model.to_string())
            .map_err(|e| format!("png model chunk: {e}"))?;
        encoder
            .add_ztxt_chunk("params_json".to_string(), meta.params_json())
            .map_err(|e| format!("png params chunk: {e}"))?;
        encoder
            .add_ztxt_chunk("version".to_string(), app_version().to_string())
            .map_err(|e| format!("png version chunk: {e}"))?;
        // Touch ZTXtChunk to silence the unused-import lint when the
        // compress-text feature is off in a downstream build.
        let _ = std::marker::PhantomData::<ZTXtChunk>;

        let mut writer = encoder
            .write_header()
            .map_err(|e| format!("png header: {e}"))?;
        writer
            .write_image_data(rgb8)
            .map_err(|e| format!("png idat: {e}"))?;
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn params_json_is_deterministic() {
        let m = PngMetadata {
            prompt: "a cat",
            model: "black-forest-labs/FLUX.1-schnell",
            width: 1024,
            height: 1024,
            steps: 4,
            cfg: 0.0,
            seed: 42,
            offload: false,
        };
        let j1 = m.params_json();
        let j2 = m.params_json();
        assert_eq!(j1, j2);
        // Spot-check the schema — keys must appear in declared order so the
        // chunk content doesn't churn between identical runs.
        assert!(j1.starts_with("{\"width\":1024,"));
        assert!(j1.contains("\"seed\":42"));
    }

    #[test]
    fn app_version_resolves_to_cargo_pkg() {
        assert!(!app_version().is_empty());
    }
}
